version: '3.8'

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - api
  
  api:
    depends_on:
      - mongodb
    build: ./api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - NODE_ENV="production"
      - PORT=8080
      - JWT_SECRET="7D6425FAC26477182B78C8F2F39CE"
      - JWT_EXPIRATION_IN_MINUTES=1440
      - MONGO_URI="mongodb://127.0.0.1:27018/blend"
      - EMAIL_FROM_NAME="iBox"
      - EMAIL_FROM_ADDRESS="no-reply@ibox.co.id"
      - EMAIL_SMTP_DOMAIN_MAILGUN="ibox.co.id"
      - EMAIL_SMTP_API_MAILGUN=123456
      - FRONTEND_URL=http://localhost:3005
      - BECKEND_URL=http://localhost:8080/blend/api
      - EMEDREC_URL="http://localhost:8080/blend/api/uploads/"
      - USE_REDIS=false
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - MJ_API_KEY="a45126939c9654f1ee368d2203ad5d10"
      - MJ_API_SECRET="fdd85cd7b7edb1afb50eebfbc563169a"
      - UPLOAD_PATH="/public/uploads/"
      - EMAILJS_SERVICE_ID="service_v0cnu8a"
      - EMAILJS_VERIFY_TEMPLATE_ID="template_gc74i5u"
      - EMAILJS_PUBLIC_KEY="eS4Hz49dVTp7fxaav"
      - EMAILJS_USER_ID="eS4Hz49dVTp7fxaav"
      - EMAILJS_ACCESS_TOKEN="kUhqREM7THGaezM_DriQd"
      - EMAILJS_PRIVATE_KEY="kUhqREM7THGaezM_DriQd"
    networks:
      - api
      - backend
      - frontend
  
  frontend:
    depends_on:
      - api
    build:
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
    networks:
      - frontend 

  backend:
    depends_on:
      - api
    build:
      context: ./backend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    env_file: ./.env
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    environment:
      - NODE_ENV="production"
      - REACT_APP_PERMISSIONS_SOURCE="ADMIN"
      - REACT_APP_SOURCE="ADMIN"
      - REACT_API_URL="http://localhost:8080/blend/api/"
      - REACT_BASE_URL="http://localhost:8080"
      - REACT_UPLOAD_PATH="/uploads/"
      - SKIP_PREFLIGHT_CHECK=true
    networks:
      - backend

volumes: 
  db:

networks:
  api:
  backend:
  frontend:
  nginx: